package PackMain;

import PackFunc.funcDb;
import PackFunc.funcLicence;
import java.net.SocketException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dynaglien
 */
public class FenDbExt extends javax.swing.JFrame {
    funcDb fdb = new funcDb();

    /**
     * Creates new form pageOption
     */
    public FenDbExt() {
        initComponents();
        labTitre.setText(PackFunc.Var.bundle.getString("param.dbext.titre"));
        labAd.setText(PackFunc.Var.bundle.getString("param.dbext.address"));
        labPort.setText(PackFunc.Var.bundle.getString("param.dbext.port"));
        labNom.setText(PackFunc.Var.bundle.getString("param.dbext.nom"));
        labUser.setText(PackFunc.Var.bundle.getString("param.dbext.user"));
        labPass.setText(PackFunc.Var.bundle.getString("param.dbext.pass"));
        labDelais.setText(PackFunc.Var.bundle.getString("param.dbext.delais"));
        cbPurge.setText(PackFunc.Var.bundle.getString("param.dbext.purge"));

        funcLicence fl = new funcLicence();
        try {
            if(fl.validLicense() == true){
                affichage();
            }else{
                labTitre.setText(PackFunc.Var.bundle.getString("licence.invalide"));
                btnValid.setVisible(false);
            }
        } catch (SocketException ex) {
            Logger.getLogger(FenRecap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void affichage(){
        tfAdDb.setText(fdb.paramLire("dbext_adress", "param"));
        tfPortDb.setText(fdb.paramLire("dbext_port", "param"));
        tfDbNom.setText(fdb.paramLire("dbext_name", "param"));
        tfUser.setText(fdb.paramLire("dbext_user", "param"));
        tfPass.setText(fdb.paramLire("dbext_pass", "param"));
        String delais = "5 min";
        if(fdb.paramLire("dbext_delais", "param").equals("300")){ delais = "5 min"; }
        else if(fdb.paramLire("dbext_delais", "param").equals("3600")){ delais = "1 h"; }
        else if(fdb.paramLire("dbext_delais", "param").equals("21600")){ delais = "6 h"; }
        else if(fdb.paramLire("dbext_delais", "param").equals("86400")){ delais = "24 h"; }
        else if(fdb.paramLire("dbext_delais", "param").equals("172800")){ delais = "2 jours"; }
        else if(fdb.paramLire("dbext_delais", "param").equals("604800")){ delais = "7 jours"; }
        else { delais = "5 min"; }
        tfDelais.setSelectedItem(delais);
        if(fdb.paramLire("dbext_purge", "param").equals("1")){
            cbPurge.setSelected(true);
        }
        else{
            cbPurge.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTitre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labAd = new javax.swing.JLabel();
        labPort = new javax.swing.JLabel();
        labUser = new javax.swing.JLabel();
        labPass = new javax.swing.JLabel();
        labDelais = new javax.swing.JLabel();
        tfAdDb = new javax.swing.JTextField();
        tfPortDb = new javax.swing.JTextField();
        tfUser = new javax.swing.JTextField();
        tfPass = new javax.swing.JTextField();
        tfDelais = new javax.swing.JComboBox<>();
        labNom = new javax.swing.JLabel();
        tfDbNom = new javax.swing.JTextField();
        cbPurge = new javax.swing.JCheckBox();
        btnValid = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        labTitre.setBackground(new java.awt.Color(51, 102, 255));
        labTitre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labTitre.setForeground(new java.awt.Color(255, 255, 255));
        labTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitre.setText("Mail recapitulatif");
        labTitre.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labAd.setText("Adresse Db : ");

        labPort.setText("Port Db : ");

        labUser.setText("User Db : ");

        labPass.setText("Pass Db : ");

        labDelais.setText("Délais :");

        tfDelais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 min", "1 h", "6 h", "24 h", "2 jours", "7 jours" }));
        tfDelais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDelaisActionPerformed(evt);
            }
        });

        labNom.setText("Db Nom :");

        cbPurge.setText("Purger la base");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labPass)
                            .addComponent(labDelais))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPass)
                            .addComponent(tfDelais, 0, 203, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labUser)
                            .addComponent(labPort)
                            .addComponent(labAd)
                            .addComponent(labNom))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDbNom)
                            .addComponent(tfAdDb)
                            .addComponent(tfPortDb)
                            .addComponent(tfUser)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbPurge)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labAd)
                    .addComponent(tfAdDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPort)
                    .addComponent(tfPortDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNom)
                    .addComponent(tfDbNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUser)
                    .addComponent(tfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPass)
                    .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDelais)
                    .addComponent(tfDelais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbPurge)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btnValid.setText("Valider");
        btnValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnValid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnValid)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidActionPerformed
System.out.println(tfDelais.getSelectedItem());
        fdb.paramEcrit("dbext_adress", tfAdDb.getText(), "param");
        fdb.paramEcrit("dbext_port", tfPortDb.getText(), "param");
        fdb.paramEcrit("dbext_name", tfDbNom.getText(), "param");
        fdb.paramEcrit("dbext_user", tfUser.getText(), "param");
        fdb.paramEcrit("dbext_pass", tfPass.getText(), "param");
        String delais = null;
        if(tfDelais.getSelectedItem().equals("5 min")){ delais = "300"; }
        else if(tfDelais.getSelectedItem().equals("1 h")){ delais = "3600"; }
        else if(tfDelais.getSelectedItem().equals("6 h")){ delais = "21600"; }
        else if(tfDelais.getSelectedItem().equals("24 h")){ delais = "86400"; }
        else if(tfDelais.getSelectedItem().equals("2 jours")){ delais = "172800"; }
        else if(tfDelais.getSelectedItem().equals("7 jours")){ delais = "604800"; }
        
        String purge;
        if(cbPurge.isSelected()){
            purge = "1";
        }else{  purge = "0"; }
        fdb.paramEcrit("dbext_delais", delais, "param");
        fdb.paramEcrit("dbext_purge", purge, "param");
        dispose();
    }//GEN-LAST:event_btnValidActionPerformed

    private void tfDelaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDelaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDelaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenDbExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenDbExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenDbExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenDbExt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenDbExt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValid;
    private javax.swing.JCheckBox cbPurge;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labAd;
    private javax.swing.JLabel labDelais;
    private javax.swing.JLabel labNom;
    private javax.swing.JLabel labPass;
    private javax.swing.JLabel labPort;
    private javax.swing.JLabel labTitre;
    private javax.swing.JLabel labUser;
    private javax.swing.JTextField tfAdDb;
    private javax.swing.JTextField tfDbNom;
    private javax.swing.JComboBox<String> tfDelais;
    private javax.swing.JTextField tfPass;
    private javax.swing.JTextField tfPortDb;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
