/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackMain;

import PackThread.threadHisto;
import PackThread.threadPrepaPing;
import PackThread.threadLanceMailRecap;
import PackThread.threadPrepaAj;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import PackFunc.funcDb;
import PackFunc.funcIp;
import PackFunc.funcLicence;
import PackFunc.funcMain;
import PackFunc.funcMiseAJour;
import java.awt.event.KeyEvent;


/**
 *
 * @author Hemge
 */
public final class FenMain extends javax.swing.JFrame {
    funcMain fun = new funcMain();
    funcIp funIp = new funcIp();
    funcDb fdb = new funcDb();
    
    /**
     * Creates new form mainAcc
     */
    public FenMain(){
        fun.testOs();
        File fichier = new File(PackFunc.Var.path+"/db/ip.pigo");
        fichier.delete();
        initComponents();
        fun.dossCree();
        labVersion.setText("PingOuin version "+PackFunc.Var.version);
        try {
            fun.connectParam();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FenMain.class.getName()).log(Level.SEVERE, null, ex);
            fun.ecritLogs(ex, " - "+getClass().getName());        }
        progerAjout.setVisible(false);
        btnLancer.setBackground(Color.red);
        
        
// Test mise à jour
        funcMiseAJour maj = new funcMiseAJour();
        if(maj.majDispo() == true){
            labMaj.setText("Mise a jour disponible");
            labMaj.setForeground(Color.red);
        }else{
            labMaj.setText("A jour");
            labMaj.setForeground(Color.white);
        }
        
// Création des tables

        funcDb funDb = new funcDb();
        fun.connectHist();
        funDb.creerTables();
        funDb.tablesRemplir();
        funDb.tableIpCree();
        licence();
        tfPremIp.setText(funIp.ipPc());
        fun.listeSites();
        threadHisto th = new threadHisto();
        //th.start();
        
// Cocher ou non menus
    if(funDb.paramLire("mail_envoie", "param").equals("1")){ menEnvoieMail.setSelected(true); } else{ menEnvoieMail.setSelected(false); }
    if(funDb.paramLire("pop_up", "param").equals("1")){ menPopup.setSelected(true); } else{ menPopup.setSelected(false); }
    if(funDb.paramLire("mail_rapport", "param").equals("1")){ menEnvoieRapports.setSelected(true); } else{ menEnvoieRapports.setSelected(false); }
    if(funDb.paramLire("archives", "param").equals("1")){ menArchives.setSelected(true); } else{ menArchives.setSelected(false); }
    if(funDb.paramLire("dbExt", "param").equals("1")){ menDbExt.setSelected(true); } else{ menDbExt.setSelected(false); }

    
    
        fdb.listeIp();
    }
    
    
    /**
     * Test de la licence
     */
    public void licence(){
        try {
            funcLicence fl = new funcLicence();
            if(fl.validLicense() == true){
                menEnvoieMail.setVisible(true);
                menEnvoieRapports.setVisible(true);
                menArchives.setVisible(true);
                menDbExt.setVisible(true);
                
                
            }else{
                menEnvoieMail.setVisible(false);
                menEnvoieRapports.setVisible(false);
                menArchives.setVisible(false);
                menDbExt.setVisible(true);
            }
        } catch (SocketException ex) {
            Logger.getLogger(FenMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLancer = new javax.swing.JToggleButton();
        progerAjout = new javax.swing.JProgressBar();
        labMaj = new javax.swing.JLabel();
        comboTri = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfPremIp = new javax.swing.JTextField();
        spinPlage = new javax.swing.JSpinner();
        cbTout = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labDelaisPing = new javax.swing.JLabel();
        slidDelaisPing = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        listeSite = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        labThreadOuvert = new javax.swing.JLabel();
        labThreadFerme = new javax.swing.JLabel();
        labVersion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPrinc = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tfNom = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        labIp = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menEnvoieMail = new javax.swing.JCheckBoxMenuItem();
        menEnvoieRapports = new javax.swing.JCheckBoxMenuItem();
        menPopup = new javax.swing.JCheckBoxMenuItem();
        menArchives = new javax.swing.JCheckBoxMenuItem();
        menDbExt = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PingOuin");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        btnLancer.setText("Lancer le ping");
        btnLancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancerActionPerformed(evt);
            }
        });

        progerAjout.setMaximum(254);

        labMaj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labMaj.setForeground(new java.awt.Color(255, 255, 255));
        labMaj.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labMaj.setText("A jour");

        comboTri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trier par", "IP", "Nom" }));
        comboTri.setMaximumSize(new java.awt.Dimension(47, 20));
        comboTri.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTriItemStateChanged(evt);
            }
        });
        comboTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnLancer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboTri, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progerAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(labMaj, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnLancer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(labMaj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progerAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajout IP");

        tfPremIp.setToolTipText("Première IP");

        spinPlage.setToolTipText("Nombres d'hotes à ajouter");
        spinPlage.setValue(1);

        cbTout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plage", "Repondant" }));
        cbTout.setToolTipText("Ajouter toute la plage ou seulement les hotes répondant");
        cbTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbToutActionPerformed(evt);
            }
        });

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTout, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfPremIp)
                    .addComponent(spinPlage)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfPremIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(spinPlage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Delais entre 2 pings");

        labDelaisPing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labDelaisPing.setText("5 s");

        slidDelaisPing.setValue(5);
        slidDelaisPing.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slidDelaisPingStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(labDelaisPing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(slidDelaisPing, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addComponent(slidDelaisPing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labDelaisPing)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        listeSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeSiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listeSite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listeSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        labThreadOuvert.setForeground(new java.awt.Color(255, 255, 255));
        labThreadOuvert.setText("Thread : 0 / ");

        labThreadFerme.setForeground(new java.awt.Color(255, 255, 255));

        labVersion.setForeground(new java.awt.Color(255, 255, 255));
        labVersion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labVersion.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(labThreadOuvert, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labThreadFerme, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labThreadOuvert, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labThreadFerme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(labVersion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tabPrinc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabPrinc.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabPrinc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tabPrincFocusLost(evt);
            }
        });
        tabPrinc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPrincMouseClicked(evt);
            }
        });
        tabPrinc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabPrincKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabPrinc);

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        labIp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNom)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(labIp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(labIp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setText("Ouvrir navigateur");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Effacer ip");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Fichier");

        jMenuItem1.setText("Imprimer");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Enregistrer la plage");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem8.setText("Gestion des sites");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem3.setText("Mise a jour");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Quitter");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Options");

        menEnvoieMail.setSelected(true);
        menEnvoieMail.setText("Envoie de mails");
        menEnvoieMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menEnvoieMailActionPerformed(evt);
            }
        });
        jMenu2.add(menEnvoieMail);

        menEnvoieRapports.setSelected(true);
        menEnvoieRapports.setText("Envoie de rapports");
        menEnvoieRapports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menEnvoieRapportsActionPerformed(evt);
            }
        });
        jMenu2.add(menEnvoieRapports);

        menPopup.setSelected(true);
        menPopup.setText("PopUp");
        menPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPopupActionPerformed(evt);
            }
        });
        jMenu2.add(menPopup);

        menArchives.setSelected(true);
        menArchives.setText("Ecrire les archives");
        menArchives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menArchivesActionPerformed(evt);
            }
        });
        jMenu2.add(menArchives);

        menDbExt.setSelected(true);
        menDbExt.setText("Base de donnée externe");
        menDbExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menDbExtActionPerformed(evt);
            }
        });
        jMenu2.add(menDbExt);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Paramètres");

        jMenuItem5.setText("Paramètres généraux");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Envoie Recap");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem11.setText("Db Externe");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem7.setText("License");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("?");

        jMenuItem9.setText("A propos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("Site internet");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FenParam pp = new FenParam();
        pp.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FenRecap pr = new FenRecap();
        pr.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FenLicence pl = new FenLicence();
        pl.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void listeSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeSiteActionPerformed
        PackFunc.Var.stopPing = true;
        PackFunc.Var.dbSite = (String) listeSite.getSelectedItem()+".pigo";
        btnLancer.setText("Start");
        btnLancer.setBackground(Color.red);
        fun.connectSite();
        fdb.listeIp();
        //threadHisto th = new threadHisto();
        //th.start();
        
    }//GEN-LAST:event_listeSiteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        threadPrepaAj tpaj = new threadPrepaAj(tfPremIp.getText(), (String) cbTout.getSelectedItem(), (Integer) spinPlage.getValue());
        tpaj.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbToutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbToutActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        fun.quit();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            fdb.dbErase();
        } catch (ClassNotFoundException ex) {
            fun.ecritLogs(ex, " - "+getClass().getName());
        }
        PackFunc.Var.stopPing = true;
        btnLancer.setText("Start");
        btnLancer.setBackground(Color.red);
        fdb.listeIp();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnLancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancerActionPerformed
        funcDb funDb = new funcDb();
        threadPrepaPing tpp = new threadPrepaPing();
        if(FenMain.btnLancer.isSelected()){
            FenMain.btnLancer.setText("Stop");
            FenMain.btnLancer.setBackground(Color.green);
            if(funDb.paramLire("archives", "param").equals("1")){
                
                fun.connectHist();
                threadHisto th = new threadHisto();
                th.start();
            }
            
            PackFunc.Var.stopPing = false;
            tpp.start();
            threadLanceMailRecap tpmr = new threadLanceMailRecap();
            tpmr.start();
        }else{
            FenMain.btnLancer.setText("Start");
            FenMain.btnLancer.setBackground(Color.red);
            PackFunc.Var.stopPing = true;           
        }
    }//GEN-LAST:event_btnLancerActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FenSiteNouveau psn = new FenSiteNouveau();
        psn.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tabPrincMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPrincMouseClicked

        int buttonDown = evt.getButton();
        Integer row = tabPrinc.getSelectedRow();
        funcIp.rowNum = (tabPrinc.getModel().getValueAt(row, 0).toString());
        
        JPopupMenu menuIp = new JPopupMenu();
        JMenuItem ouvrir = new JMenuItem("Ouvrir dans le navigateur");
        menuIp.add(ouvrir);
        JMenuItem suppr = new JMenuItem("Supprimer");
        menuIp.add(suppr);
        JMenuItem hist = new JMenuItem("Historique");
        if(fdb.paramLire("archives", "param").equals("1")){
            menuIp.add(hist);
        }
        
        ouvrir.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    try {
                        Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler \"http://"+labIp.getText()+"\""); //NOI18N
                    } catch (IOException ex) {

                    }
            }
        });
        suppr.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    fdb.ipSiteErase(funcIp.rowNum);
                    btnLancer.setText("Start");
                    btnLancer.setBackground(Color.red);
                    fdb.listeIp();
            }
        });
        hist.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    
                    FenHist.ipHist = funcIp.rowNum;
                    FenHist fh = new FenHist();
                    fh.show();
            }
        });
        
        switch (buttonDown) {
        // Bouton GAUCHE enfoncé
            case MouseEvent.BUTTON1:
                funIp.nomHote();
                break;
        // Bouton du MILIEU enfoncé
            case MouseEvent.BUTTON2:
                
                break;
        // Bouton DROIT enfoncé
            case MouseEvent.BUTTON3:
                menuIp.show(tabPrinc, evt.getPoint().x, evt.getPoint().y);
                break;
            default:
                break;
        }






        
        
    }//GEN-LAST:event_tabPrincMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nom = tfNom.getText();
        
        fdb.dbIpEcrit(funcIp.rowNum, nom, "nom");
        fdb.listeIp();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void menEnvoieMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menEnvoieMailActionPerformed
        if(menEnvoieMail.isSelected() == true){ fdb.paramEcrit("mail_envoie", "1", "param"); }else{ fdb.paramEcrit("mail_envoie", "0", "param"); }
    }//GEN-LAST:event_menEnvoieMailActionPerformed

    private void menEnvoieRapportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menEnvoieRapportsActionPerformed
        if(menEnvoieRapports.isSelected() == true){ fdb.paramEcrit("mail_rapport", "1", "param"); }else{ fdb.paramEcrit("mail_rapport", "0", "param"); }
    }//GEN-LAST:event_menEnvoieRapportsActionPerformed

    private void menPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPopupActionPerformed
        if(menPopup.isSelected() == true){ fdb.paramEcrit("pop_up", "1", "param"); }else{ fdb.paramEcrit("pop_up", "0", "param"); }
    }//GEN-LAST:event_menPopupActionPerformed

    private void menArchivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menArchivesActionPerformed
        if(menArchives.isSelected() == true){
            fdb.paramEcrit("archives", "1", "param"); 
        }else{ 
            fdb.paramEcrit("archives", "0", "param"); 
        }
        //threadHisto th = new threadHisto();
        //th.start();
    }//GEN-LAST:event_menArchivesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler \"http://"+labIp.getText()+"\""); //NOI18N
        } catch (IOException ex) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FenGestionSite pgs = new FenGestionSite();
        pgs.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        funcMiseAJour maj = new funcMiseAJour();
        maj.update();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        fdb.ipSiteErase(funcIp.rowNum);
        btnLancer.setText("Start");
        btnLancer.setBackground(Color.red);
        fdb.listeIp();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler \"https://prog.serenity.xyz/\""); //NOI18N
        } catch (IOException ex) {
            fun.ecritLogs(ex, " - "+getClass().getName());
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FenAPropos pap = new FenAPropos();
        pap.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void slidDelaisPingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidDelaisPingStateChanged
        // TODO add your handling code here:
        long delaisPause = Long.parseLong(String.valueOf(slidDelaisPing.getValue()));
        
        if(delaisPause >= 60 && delaisPause < 3600){
            delaisPause = delaisPause / 60;
            labDelaisPing.setText(Long.toString(delaisPause)+" min");
        }
        else if(delaisPause >= 3600){
            delaisPause = delaisPause / 3600;
            labDelaisPing.setText(Long.toString(delaisPause)+" h");
        }else if(delaisPause <= 0){
            PackThread.threadPop tp = new PackThread.threadPop("Veuillez entrer une valeur supérieure à Zéro");
            tp.start();
            slidDelaisPing.setValue(5);
        }else{
            labDelaisPing.setText(Long.toString(delaisPause)+" s");
        }
        
        PackFunc.Var.delaisPause = (Integer) slidDelaisPing.getValue();
    }//GEN-LAST:event_slidDelaisPingStateChanged

    private void comboTriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTriItemStateChanged
        
    }//GEN-LAST:event_comboTriItemStateChanged

    private void comboTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTriActionPerformed
        if(comboTri.getSelectedItem().equals("Trier par")){
            PackFunc.Var.tri = "IP";
        }else{
            PackFunc.Var.tri = (String) comboTri.getSelectedItem();
        }
        fdb.listeIp();
        PackFunc.Var.stopPing = true;
        btnLancer.setText("Start");
        btnLancer.setBackground(Color.red);
        System.out.println(PackFunc.Var.tri);
    }//GEN-LAST:event_comboTriActionPerformed

    private void tabPrincFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabPrincFocusLost
    
    

// TODO add your handling code here:
    }//GEN-LAST:event_tabPrincFocusLost

    private void tabPrincKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabPrincKeyPressed
        if (KeyEvent.VK_ENTER==evt.getKeyCode()){
            String ob = tabPrinc.getValueAt(tabPrinc.getSelectedRow(),1).toString();
            String ob1 = tabPrinc.getValueAt(tabPrinc.getSelectedRow(),0).toString();
            fdb.dbIpEcrit(ob1, ob, "nom");
            fdb.listeIp();
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_tabPrincKeyPressed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FenDbExt fdb = new FenDbExt();
        fdb.show();  
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void menDbExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menDbExtActionPerformed
        if(menDbExt.isSelected() == true){
            fdb.paramEcrit("dbExt", "1", "param"); 
        }else{ 
            fdb.paramEcrit("dbExt", "0", "param"); 
        }
    }//GEN-LAST:event_menDbExtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FenMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JToggleButton btnLancer;
    private javax.swing.JComboBox<String> cbTout;
    private javax.swing.JComboBox<String> comboTri;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JLabel labDelaisPing;
    public static javax.swing.JLabel labIp;
    private javax.swing.JLabel labMaj;
    public static javax.swing.JLabel labThreadFerme;
    public static javax.swing.JLabel labThreadOuvert;
    private javax.swing.JLabel labVersion;
    public static javax.swing.JComboBox<String> listeSite;
    private javax.swing.JCheckBoxMenuItem menArchives;
    private javax.swing.JCheckBoxMenuItem menDbExt;
    private javax.swing.JCheckBoxMenuItem menEnvoieMail;
    private javax.swing.JCheckBoxMenuItem menEnvoieRapports;
    private javax.swing.JCheckBoxMenuItem menPopup;
    public static javax.swing.JProgressBar progerAjout;
    private javax.swing.JSpinner slidDelaisPing;
    private javax.swing.JSpinner spinPlage;
    public static javax.swing.JTable tabPrinc;
    public static javax.swing.JTextField tfNom;
    public static javax.swing.JTextField tfPremIp;
    // End of variables declaration//GEN-END:variables
}
