/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackMain;

import PackFunc.funcDb;
import PackFunc.funcLicence;
import PackThread.threadPop;
import java.io.IOException;
import java.net.SocketException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dynaglien
 */
public class FenParam extends javax.swing.JFrame {
    funcDb fdb = new funcDb();
    funcLicence fl = new funcLicence();
    PackFunc.funcMain fun = new PackFunc.funcMain();
    /**
     * Creates new form pageParam
     */
    public FenParam() {
        initComponents();
        labParam.setText(PackFunc.Var.bundle.getString("param.titre"));
        labSite.setText(PackFunc.Var.bundle.getString("param.site"));
        labMail.setText(PackFunc.Var.bundle.getString("param.mail"));
        
        btnValid.setText(PackFunc.Var.bundle.getString("btn.valid"));
        
        btnMailParam.setText(PackFunc.Var.bundle.getString("param.mail.param"));
        btnRecap.setText(PackFunc.Var.bundle.getString("param.recap"));
        btnDbExt.setText(PackFunc.Var.bundle.getString("param.dbext"));
        btnLi.setText(PackFunc.Var.bundle.getString("param.licen"));
        btnRac.setText(PackFunc.Var.bundle.getString("param.rac"));
        labAutre.setText(PackFunc.Var.bundle.getString("param.autre"));
        labLangue.setText(PackFunc.Var.bundle.getString("param.langue"));
        paramAffiche();
    }
    
    public void paramAffiche(){
        tfSite.setText(fdb.paramLire("site", "param"));
        tfMail.setText(fdb.paramLire("mail", "param"));
        cbLangue.setSelectedItem(fdb.paramLire("langue", "param"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labParam = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labSite = new javax.swing.JLabel();
        labMail = new javax.swing.JLabel();
        tfMail = new javax.swing.JTextField();
        tfSite = new javax.swing.JTextField();
        cbLangue = new javax.swing.JComboBox<>();
        labLangue = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labAutre = new javax.swing.JLabel();
        btnMailParam = new javax.swing.JButton();
        btnRecap = new javax.swing.JButton();
        btnDbExt = new javax.swing.JButton();
        btnLi = new javax.swing.JButton();
        btnRac = new javax.swing.JButton();
        btnValid = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 204, 255));
        setLocationByPlatform(true);

        labParam.setBackground(new java.awt.Color(51, 102, 255));
        labParam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labParam.setForeground(new java.awt.Color(255, 255, 255));
        labParam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labParam.setText("Paramètres");
        labParam.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labSite.setText("Site");

        labMail.setText("Mail à envoyer");

        cbLangue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "en_US", "fr_FR" }));

        labLangue.setText("Mail à envoyer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labSite)
                    .addComponent(labMail)
                    .addComponent(labLangue))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMail)
                    .addComponent(tfSite, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(cbLangue, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labSite)
                    .addComponent(tfSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLangue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labLangue))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labAutre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labAutre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labAutre.setText("jLabel1");

        btnMailParam.setText("Envoie de mails");
        btnMailParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMailParamActionPerformed(evt);
            }
        });

        btnRecap.setText("Envoie de recap");
        btnRecap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecapActionPerformed(evt);
            }
        });

        btnDbExt.setText("Db Externe");
        btnDbExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDbExtActionPerformed(evt);
            }
        });

        btnLi.setText("Licence");
        btnLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiActionPerformed(evt);
            }
        });

        btnRac.setText("jButton1");
        btnRac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labAutre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDbExt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMailParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRecap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(labAutre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMailParam)
                    .addComponent(btnRecap))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDbExt)
                    .addComponent(btnLi))
                .addGap(18, 18, 18)
                .addComponent(btnRac)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        btnValid.setText("Valider");
        btnValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnValid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labParam, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnValid)
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidActionPerformed
        fdb.paramEcrit("site", tfSite.getText(), "param");
        fdb.paramEcrit("mail", tfMail.getText(), "param");
        fdb.paramEcrit("langue", cbLangue.getSelectedItem().toString(), "param");
        PackThread.threadPop tpop = new PackThread.threadPop(PackFunc.Var.bundle.getString("param.langue.change"));
        tpop.start();
        
        dispose();
    }//GEN-LAST:event_btnValidActionPerformed

    private void btnMailParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMailParamActionPerformed

                FenParamMail pr = new FenParamMail();
                pr.show();
                dispose();
    }//GEN-LAST:event_btnMailParamActionPerformed

    private void btnRecapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecapActionPerformed
        
                FenRecap pr = new FenRecap();
                pr.show();
                dispose();
    }//GEN-LAST:event_btnRecapActionPerformed

    private void btnDbExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDbExtActionPerformed
        
                FenDbExt pr = new FenDbExt();
                pr.show();
            dispose();
    }//GEN-LAST:event_btnDbExtActionPerformed

    private void btnLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiActionPerformed
        
                FenLicence pr = new FenLicence();
                pr.show();
            dispose();
    }//GEN-LAST:event_btnLiActionPerformed

    private void btnRacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRacActionPerformed
        PackFunc.FuncRac rac = new PackFunc.FuncRac();
        try {
            rac.creerRacBureau();
            rac.creerRacDemarrer();
        } catch (IOException | InterruptedException ex) {
            Logger.getLogger(FenParam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenParam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDbExt;
    private javax.swing.JButton btnLi;
    private javax.swing.JButton btnMailParam;
    private javax.swing.JButton btnRac;
    private javax.swing.JButton btnRecap;
    private javax.swing.JButton btnValid;
    private javax.swing.JComboBox<String> cbLangue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labAutre;
    private javax.swing.JLabel labLangue;
    private javax.swing.JLabel labMail;
    private javax.swing.JLabel labParam;
    private javax.swing.JLabel labSite;
    private javax.swing.JTextField tfMail;
    private javax.swing.JTextField tfSite;
    // End of variables declaration//GEN-END:variables
}
