/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PackMain;

import PackFunc.funcDb;
import PackFunc.funcLicence;
import java.net.SocketException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dynaglien
 */
public class FenParamMail extends javax.swing.JFrame {
    funcDb fdb = new funcDb();
    /**
     * Creates new form pageParam
     */
    public FenParamMail() {
        initComponents();
        funcLicence fl = new funcLicence();
        labParam.setText(PackFunc.Var.bundle.getString("param.mail.titre"));
        labServ.setText(PackFunc.Var.bundle.getString("param.mail.serveur"));
        labPort.setText(PackFunc.Var.bundle.getString("param.mail.port"));
        labUser.setText(PackFunc.Var.bundle.getString("param.mail.user"));
        labPass.setText(PackFunc.Var.bundle.getString("param.mail.pass"));
        labMail.setText(PackFunc.Var.bundle.getString("param.mail.mail"));
        cbEnvoieMail.setText(PackFunc.Var.bundle.getString("param.mail.envoie"));
        butValid.setText(PackFunc.Var.bundle.getString("btn.valid"));
        try {
            if(fl.validLicense() == true){
                    
                paramAffiche();
            }else {
                labParam.setText(PackFunc.Var.bundle.getString("licence.invalide"));
                butValid.setVisible(false);
            }   
        } catch (SocketException ex) {
            Logger.getLogger(FenParamMail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    public void paramAffiche(){
        
        tfSmtpServ.setText(fdb.paramLire("smtp_serv", "param"));
        tfSmtpPort.setText(fdb.paramLire("smtp_port", "param"));
        tfSmtpUser.setText(fdb.paramLire("smtp_user", "param"));
        tfSmtpPass.setText(fdb.paramLire("smtp_pass", "param"));
        tfSmtpMail.setText(fdb.paramLire("smtp_mail", "param"));
        if(fdb.paramLire("mail_rapport", "param").equals("1")){
            cbEnvoieMail.setSelected(true);
        }else{
            cbEnvoieMail.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labParam = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labServ = new javax.swing.JLabel();
        labUser = new javax.swing.JLabel();
        labPort = new javax.swing.JLabel();
        labMail = new javax.swing.JLabel();
        labPass = new javax.swing.JLabel();
        tfSmtpServ = new javax.swing.JTextField();
        tfSmtpPort = new javax.swing.JTextField();
        tfSmtpUser = new javax.swing.JTextField();
        tfSmtpMail = new javax.swing.JTextField();
        tfSmtpPass = new javax.swing.JTextField();
        cbEnvoieMail = new javax.swing.JCheckBox();
        butValid = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 204, 255));
        setLocationByPlatform(true);

        labParam.setBackground(new java.awt.Color(51, 102, 255));
        labParam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labParam.setForeground(new java.awt.Color(255, 255, 255));
        labParam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labParam.setText("Paramètres");
        labParam.setOpaque(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labServ.setText("Serveur SMTP");

        labUser.setText("User SMTP");

        labPort.setText("Port SMTP");

        labMail.setText("Mail SMTP");

        labPass.setText("Pass SMTP");

        cbEnvoieMail.setText("jCheckBox1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labPass)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(cbEnvoieMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(tfSmtpPass))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labServ)
                            .addComponent(labPort)
                            .addComponent(labUser)
                            .addComponent(labMail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSmtpMail, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(tfSmtpUser)
                            .addComponent(tfSmtpPort)
                            .addComponent(tfSmtpServ))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labServ)
                    .addComponent(tfSmtpServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPort)
                    .addComponent(tfSmtpPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUser)
                    .addComponent(tfSmtpUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labMail)
                    .addComponent(tfSmtpMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPass)
                    .addComponent(tfSmtpPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(cbEnvoieMail)
                .addContainerGap())
        );

        butValid.setText("Valider");
        butValid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butValid, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labParam, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butValid)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butValidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValidActionPerformed
        
        fdb.paramEcrit("smtp_serv", tfSmtpServ.getText(), "param");
        fdb.paramEcrit("smtp_port", tfSmtpPort.getText(), "param");
        fdb.paramEcrit("smtp_user", tfSmtpUser.getText(), "param");
        fdb.paramEcrit("smtp_pass", tfSmtpPass.getText(), "param");
        fdb.paramEcrit("smtp_mail", tfSmtpMail.getText(), "param");
        dispose();
    }//GEN-LAST:event_butValidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenParamMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenParamMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenParamMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenParamMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenParamMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butValid;
    private javax.swing.JCheckBox cbEnvoieMail;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labMail;
    private javax.swing.JLabel labParam;
    private javax.swing.JLabel labPass;
    private javax.swing.JLabel labPort;
    private javax.swing.JLabel labServ;
    private javax.swing.JLabel labUser;
    private javax.swing.JTextField tfSmtpMail;
    private javax.swing.JTextField tfSmtpPass;
    private javax.swing.JTextField tfSmtpPort;
    private javax.swing.JTextField tfSmtpServ;
    private javax.swing.JTextField tfSmtpUser;
    // End of variables declaration//GEN-END:variables
}
