package PackMain;

import PackFunc.funcDb;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dynaglien
 */
public class FenRecap extends javax.swing.JFrame {
    funcDb fdb = new funcDb();
    /**
     * Creates new form pageOption
     */
    public FenRecap() {
        initComponents();
        affichage();
    }
    
    public void affichage(){
        tfHeure.setText(fdb.paramLire("PeriodeHeure", "options"));
        if(fdb.paramLire("PeriodeLun", "options").equals("1")){ cbLun.setSelected(true); }else{  cbLun.setSelected(false); }
        if(fdb.paramLire("PeriodeMar", "options").equals("1")){ cbMar.setSelected(true); }else{  cbLun.setSelected(false); }
        if(fdb.paramLire("PeriodeMerc", "options").equals("1")){ cbMerc.setSelected(true); }else{  cbLun.setSelected(false); }
        if(fdb.paramLire("PeriodeJeu", "options").equals("1")){ cbJeu.setSelected(true); }else{  cbLun.setSelected(false); }
        if(fdb.paramLire("PeriodeVen", "options").equals("1")){ cbVen.setSelected(true); }else{  cbLun.setSelected(false); }
        if(fdb.paramLire("PeriodeSam", "options").equals("1")){ cbSam.setSelected(true); }else{  cbLun.setSelected(false); }
        if(fdb.paramLire("PeriodeDim", "options").equals("1")){ cbDim.setSelected(true); }else{  cbLun.setSelected(false); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfHeure = new javax.swing.JFormattedTextField();
        cbLun = new javax.swing.JCheckBox();
        cbMar = new javax.swing.JCheckBox();
        cbMerc = new javax.swing.JCheckBox();
        cbJeu = new javax.swing.JCheckBox();
        cbVen = new javax.swing.JCheckBox();
        cbSam = new javax.swing.JCheckBox();
        cbDim = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mail recapitulatif");
        jLabel1.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Heure du mail (hh:mm)");

        tfHeure.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        cbLun.setText("lun");

        cbMar.setText("mar");

        cbMerc.setText("merc");

        cbJeu.setText("jeu");

        cbVen.setText("ven");

        cbSam.setText("sam");

        cbDim.setText("dim");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfHeure))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbLun)
                                .addGap(18, 18, 18)
                                .addComponent(cbMar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbVen)
                                .addGap(18, 18, 18)
                                .addComponent(cbSam)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbMerc)
                                .addGap(18, 18, 18)
                                .addComponent(cbJeu))
                            .addComponent(cbDim))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfHeure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLun)
                    .addComponent(cbMar)
                    .addComponent(cbMerc)
                    .addComponent(cbJeu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbVen)
                    .addComponent(cbSam)
                    .addComponent(cbDim))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(cbLun.isSelected()){
            fdb.paramEcrit("PeriodeLun", "1", "options");
        }else{
            fdb.paramEcrit("PeriodeLun", "0", "options");
        }
        if(cbMar.isSelected()){
            fdb.paramEcrit("PeriodeMar", "1", "options");
        }else{
            fdb.paramEcrit("PeriodeMar", "0", "options");
        }
        if(cbMerc.isSelected()){
            fdb.paramEcrit("PeriodeMerc", "1", "options");
        }else{
            fdb.paramEcrit("PeriodeMerc", "0", "options");
        }
        if(cbJeu.isSelected()){
            fdb.paramEcrit("PeriodeJeu", "1", "options");
        }else{
            fdb.paramEcrit("PeriodeJeu", "0", "options");
        }
        if(cbVen.isSelected()){
            fdb.paramEcrit("PeriodeVen", "1", "options");
        }else{
            fdb.paramEcrit("PeriodeVen", "0", "options");
        }
        if(cbSam.isSelected()){
            fdb.paramEcrit("PeriodeSam", "1", "options");
        }else{
            fdb.paramEcrit("PeriodeSam", "0", "options");
        }
        if(cbDim.isSelected()){
            fdb.paramEcrit("PeriodeDim", "1", "options");
        }else{
            fdb.paramEcrit("PeriodeDim", "0", "options");
        }
        fdb.paramEcrit("PeriodeHeure", tfHeure.getText(), "options");
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenRecap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenRecap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenRecap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenRecap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenRecap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbDim;
    private javax.swing.JCheckBox cbJeu;
    private javax.swing.JCheckBox cbLun;
    private javax.swing.JCheckBox cbMar;
    private javax.swing.JCheckBox cbMerc;
    private javax.swing.JCheckBox cbSam;
    private javax.swing.JCheckBox cbVen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField tfHeure;
    // End of variables declaration//GEN-END:variables
}
